[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "fem-adaptivity"
version = "1.0.0"
description = "fem adaptivity for computational electromagnetics"
readme = "README.rst"
requires-python = ">=3.10"
license = "MIT"
dependencies = ["numpy>=1.26,<3", "scikit-fem>=12,<13"]

[project.optional-dependencies]
test = ["pytest>=8,<10"]

[tool.setuptools.packages.find]
where = ["src"]
