name: fdfd
channels:
  - conda-forge
dependencies:
  - python>=3.11,<3.14
  - pip
  - numpy>=1.26,<3
  - scipy>=1.12,<2
  - matplotlib>=3.8,<4
  - h5py>=3.15,<4
  - gmsh>=4.13,<5
  - python-gmsh>=4.13,<5
  - scikit-fem>=12,<13
  - cython>=3,<4
  - setuptools>=77
  - wheel
  - pytest>=8,<10
  - docutils
  - pandas
  - tqdm
  - tk>=8.6
