[pytest]
testpaths = tests
addopts = --import-mode=importlib
pythonpath = src libraries/cem_common/src libraries/periodic_eigensolver/src solvers/fdfd/band_structure/src solvers/fdfd/mode_tracking/src solvers/fdfd/periodic_modes/src solvers/fdfd/scattering/src solvers/fdfd/waveguide_modes/src
markers =
    gmsh: test requiring Gmsh
    slow: numerical convergence or performance test
