[pytest]
testpaths = tests solvers libraries
addopts = --import-mode=importlib
pythonpath = libraries/fem_common/src solvers/fem/waveguide_modes/src solvers/fem/periodic_modes/src solvers/fem/electrostatics/src solvers/fem/waveguide_scattering/src libraries/fem_adaptivity/src libraries/periodic_eigensolver/src solvers/fdfd/waveguide_modes/src solvers/fdfd/periodic_modes/src solvers/fdfd/band_structure/src solvers/fdfd/scattering/src
markers =
    gmsh: test requiring Gmsh
    slow: numerical convergence or performance test
