name: RF_Engineering_env
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy>=1.26,<3
  - scipy>=1.12,<2
  - scikit-fem>=12,<13
  - gmsh>=4.13,<5
  - h5py>=3.15,<4
  - python-gmsh>=4.13,<5
  - meshio>=5.3,<6
  - matplotlib>=3.8,<4
  - pytest>=8,<10
  - tk>=8.6
  - pip
