# Include before project(), also for standalone application builds.
if(CMAKE_HOST_WIN32)
    if(CMAKE_GENERATOR MATCHES "MinGW|MSYS")
        message(FATAL_ERROR "MinGW is not supported. Use scripts/setup_msvc_windows.ps1 and a fresh build directory.")
    endif()
    if(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
        set(FDFD_VCPKG_TOOLCHAIN "C:/opt/vcpkg/scripts/buildsystems/vcpkg.cmake")
        if(DEFINED ENV{CMAKE_TOOLCHAIN_FILE} AND NOT "$ENV{CMAKE_TOOLCHAIN_FILE}" STREQUAL "")
            set(FDFD_VCPKG_TOOLCHAIN "$ENV{CMAKE_TOOLCHAIN_FILE}")
        endif()
        set(CMAKE_TOOLCHAIN_FILE "${FDFD_VCPKG_TOOLCHAIN}"
            CACHE FILEPATH "Windows dependency toolchain")
    endif()
    set(VCPKG_TARGET_TRIPLET "x64-windows" CACHE STRING "Windows dependency triplet")
    if(NOT VCPKG_TARGET_TRIPLET STREQUAL "x64-windows")
        message(FATAL_ERROR "Windows builds require MSVC and the x64-windows vcpkg triplet. MinGW is not supported.")
    endif()
    if(NOT EXISTS "${CMAKE_TOOLCHAIN_FILE}")
        message(FATAL_ERROR "Install vcpkg in C:/opt/vcpkg or set CMAKE_TOOLCHAIN_FILE to its vcpkg.cmake file.")
    endif()
    # Override old CC/CXX environment settings on a fresh configure. Explicit
    # compiler/cache selections are checked after project() by NativeRuntime.
    if(NOT DEFINED CMAKE_C_COMPILER)
        set(CMAKE_C_COMPILER cl CACHE FILEPATH "MSVC C compiler")
    endif()
    if(NOT DEFINED CMAKE_CXX_COMPILER)
        set(CMAKE_CXX_COMPILER cl CACHE FILEPATH "MSVC C++ compiler")
    endif()
endif()
